### PR TITLE
My take on CI :)

### PR DESCRIPTION
**Pull request by szepeviktor**
- Use GitHub Actions' built-in features
- Get tools with PHIVE
- Use Composer scripts
- Benefit!

💰💰💰💰💰

### CODE REVIEW

**Comment by szepeviktor** [comment]
@hason This is for inspiration, not expecting a merge.

See https://github.com/nektos/act for running all these locally :)

**Comment by szepeviktor** [comment]
Actually this is the womb of my first two GitHub actions: 
https://github.com/marketplace/actions/install-phive
https://github.com/marketplace/actions/install-phar-files

**Comment by peter279k** [comment]
Some files are conflicted and it should be fixed.

**Comment by szepeviktor** [comment]
@peter279k Done.

**Comment by szepeviktor** [comment]
kép

- Run unit tests on all supported versions
- Run PHPStan on the lowest: PHP 7.2
- Run PHP-CS-Fixer on the highest

**Comment by jarednova** [comment]
@szepeviktor oh hey, funny seeing you here!

**Comment by szepeviktor** [comment]
> oh hey, funny seeing you here!

@jarednova 👋

**Comment by szepeviktor** [comment]
Nowadays my default CI looks like this.

kép

**Pull request closed without merging**
